
#find GAME_ENGINE
if(JENKINS_BUILD)
	list(APPEND GAME_ENGINE_INCLUDE_LIST "${CMAKE_SOURCE_DIR}/../GameEngineLinux")
	list(APPEND GAME_ENGINE_INCLUDE_LIST "${CMAKE_SOURCE_DIR}/../GameEngineWindows")
	
	list(APPEND GAME_ENGINE_BIN_PATH "${CMAKE_SOURCE_DIR}/../GameEngineLinux/bin")
	list(APPEND GAME_ENGINE_BIN_PATH "${CMAKE_SOURCE_DIR}/../GameEngineWindows/bin")
else()
	list(APPEND GAME_ENGINE_INCLUDE_LIST "${CMAKE_SOURCE_DIR}/../GameEngine")
	
	list(APPEND GAME_ENGINE_BIN_PATH "${CMAKE_SOURCE_DIR}/../GameEngine/bin")
endif(JENKINS_BUILD)

find_path(GAME_ENGINE_INCLUDE_DIR CMakeLists.txt ${GAME_ENGINE_INCLUDE_LIST})

find_library(GAME_ENGINE_LIB NAMES GameEngine PATHS ${GAME_ENGINE_BIN_PATH})
find_library(GAME_ENGINE_COMMON_LIB NAMES common PATHS ${GAME_ENGINE_BIN_PATH})
find_library(GAME_ENGINE_QUADTREE_LIB NAMES QuadTree PATHS ${GAME_ENGINE_BIN_PATH})
find_library(GAME_ENGINE_GUI_LIB NAMES GUI PATHS ${GAME_ENGINE_BIN_PATH})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GAME_ENGINE REQUIRED_VARS GAME_ENGINE_INCLUDE_DIR GAME_ENGINE_LIB GAME_ENGINE_COMMON_LIB GAME_ENGINE_QUADTREE_LIB GAME_ENGINE_GUI_LIB)

#mark_as_advanced(GAME_ENGINE_INCLUDE_DIR GAME_ENGINE_LIB)
