
#find GAME_ENGINE

find_path(GAME_ENGINE_INCLUDE_DIR CMakeLists.txt "${CMAKE_SOURCE_DIR}/../GameEngine"
												 "${CMAKE_SOURCE_DIR}/../GameEngineLinux"
												 "${CMAKE_SOURCE_DIR}/../GameEngineWindows")

list(APPEND GAME_ENGINE_BIN_PATH "${CMAKE_SOURCE_DIR}/../GameEngine/bin")
list(APPEND GAME_ENGINE_BIN_PATH "${CMAKE_SOURCE_DIR}/../GameEngineLinux/bin")
list(APPEND GAME_ENGINE_BIN_PATH "${CMAKE_SOURCE_DIR}/../GameEngineWindows/bin")

find_library(GAME_ENGINE_LIB NAMES GameEngine PATHS ${GAME_ENGINE_BIN_PATH})
find_library(GAME_ENGINE_COMMON_LIB NAMES common PATHS ${GAME_ENGINE_BIN_PATH})
find_library(GAME_ENGINE_QUADTREE_LIB NAMES QuadTree PATHS ${GAME_ENGINE_BIN_PATH})
find_library(GAME_ENGINE_GUI_LIB NAMES GUI PATHS ${GAME_ENGINE_BIN_PATH})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GAME_ENGINE REQUIRED_VARS GAME_ENGINE_INCLUDE_DIR GAME_ENGINE_LIB GAME_ENGINE_COMMON_LIB GAME_ENGINE_QUADTREE_LIB GAME_ENGINE_GUI_LIB)

#mark_as_advanced(GAME_ENGINE_INCLUDE_DIR GAME_ENGINE_LIB)
